
# dataset info
dataset_name: "EUVP" 
dataset_path: "/mnt/data1/ImageEnhance/EUVP/Paired/"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 1000 # steps
ckpt_interval: 20  # epochs



 
